version: "2.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: benjerryapi
    ports:
      - 8080:8080
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

mongo:
  image: mongo:latest
  container_name: mongoserver
  ports:
    - 27017:27017
  healthcheck:
    test: ["CMD", "nc", " -zvv", "mongoserver", "27017"]
    timeout: 5s
    retries: 10

redis:
  image: redis:latest
  container_name: redisserver
  ports:
    - 6379:6379
  healthcheck:
    test: ["CMD", "nc", "-zvv" "redisserver", "6379"]
    timeout: 5s
    retries: 10
